# Generated by Django 6.0.7 on 2026-08-31 00:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=120)),
                ('label_font', models.CharField(choices=[('caveat', 'Caveat'), ('patrick_hand', 'Patrick Hand'), ('shadows', 'Shadows Into Light'), ('gaegu', 'Gaegu')], default='caveat', max_length=32)),
                ('cover_color', models.CharField(choices=[('cream', 'Cream'), ('blush', 'Blush pink'), ('sage', 'Sage green'), ('lavender', 'Lavender'), ('sky', 'Soft blue'), ('burgundy', 'Burgundy')], default='cream', max_length=16)),
                ('cover_pattern', models.CharField(choices=[('plain', 'Plain'), ('dots', 'Dots'), ('stripes', 'Stripes'), ('grid', 'Grid'), ('floral', 'Floral')], default='plain', max_length=16)),
                ('sticker_layout', models.JSONField(blank=True, default=list)),
                ('notebook_type', models.CharField(choices=[('class', 'Class notebook'), ('journal', 'Journal'), ('project', 'Project notebook'), ('idea', 'Idea book'), ('blank', 'Blank')], default='blank', max_length=16)),
                ('is_favorite', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notebooks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_favorite', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('notebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='notebooks.notebook')),
            ],
            options={
                'ordering': ['position', 'created_at'],
            },
        ),
    ]
