# Generated by Django 6.0.7 on 2026-09-01 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='cover_color',
            field=models.CharField(choices=[('cream', 'Cream'), ('blush', 'Bubblegum'), ('sage', 'Seafoam'), ('lavender', 'Honey'), ('sky', 'Deep Teal'), ('burgundy', 'Deep Sea')], default='cream', max_length=16),
        ),
    ]
